# SPDX-License-Identifier: BSL-1.0

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      # - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-case-conflict
      # - id: no-commit-to-branch
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.3
    hooks:
      - id: clang-format

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: shfmt
