name: Emscripten

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja

jobs:
  emcc:
    name: EMCC
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install conan
        run: |
          pip3 install "conan==1.61.0"
          conan config init
          conan config set general.revisions_enabled=1
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: Build dependencies
        run: >
          conan install
          -if build
          --build=missing
          -pr:b=default
          -pr:h="profiles/emscripten.profile"
          -s compiler.cppstd=20
          -s build_type=Release
          -c tools.system.package_manager:mode=install
          -c tools.system.package_manager:sudo=True
          .

      - name: Build & Test
        run: conan build -bf build .
