name: Emscripten

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja

jobs:
  build:
    name: Emscripten
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: CMake configure
        run: emcmake cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: Build & Test
        run: cmake --build build
