name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    name: GCC
    strategy:
      matrix:
        cxx_std: [20, 23]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install graphics dependencies
        run: >
          sudo apt install -y
          libx11-xcb-dev
          libfontenc-dev
          libxaw7-dev
          libxcomposite-dev
          libxcursor-dev
          libxdamage-dev
          libxfixes-dev
          libxi-dev
          libxinerama-dev
          libxmu-dev
          libxmuu-dev
          libxpm-dev
          libxrandr-dev
          libxres-dev
          libxss-dev
          libxtst-dev
          libxv-dev
          libxvmc-dev
          libxxf86vm-dev
          libxcb-render-util0-dev
          libxcb-xkb-dev
          libxcb-icccm4-dev
          libxcb-image0-dev
          libxcb-keysyms1-dev
          libxcb-randr0-dev
          libxcb-shape0-dev
          libxcb-sync-dev
          libxcb-xfixes0-dev
          libxcb-xinerama0-dev
          libxcb-dri3-dev
          libgl-dev

      - name: Install conan
        run: |
          pip3 install conan
          conan config init
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build - Debug
        run: |
          cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug

      - name: Build - Release
        run: |
          cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
