name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    name: GCC
    strategy:
      matrix:
        cxx_std: [20, 23]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake libgl-dev

      - name: Install conan
        run: |
          pip3 install conan
          conan config init
          conan config set tools.system.package_manager:mode=install
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build - Debug
        run: |
          cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug

      - name: Build - Release
        run: |
          cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
