name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang:
    name: Clang
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake mesa-utils freeglut3-dev

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all

      - name: Install conan
        run: |
          pip3 install --force-reinstall "conan==1.59.0"
          conan config init
          conan config set general.revisions_enabled=1
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update conf.tools.system.package_manager:mode=install default
          conan profile update conf.tools.system.package_manager:sudo=True default

      - name: CMake config
        run: cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER="clang-16" -D CMAKE_CXX_COMPILER="clang++-16"

      - name: CMake build
        run: cmake --build build --config Release
