name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  macos-13:
    name: macOS-13
    runs-on: macos-13
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ninja
        run: brew install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan profile detect -f

      - name: CMake config
        run: >
          cmake
          -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake

      - name: CMake build
        run: cmake --build build --config Release
