name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-12:
    name: macOS 12
    runs-on: macos-12
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: brew install ninja

      - name: Install conan
        run: |
          pip3 install --force-reinstall "conan==1.59.0"
          conan config init
          conan config set general.revisions_enabled=1

      - name: CMake config
        run: cmake -S. -Bbuild -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: CMake build
        run: cmake --build build --config Release
