name: Pre-Commit Hooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pre-commit

      - name: Check Pre-Commit Hooks
        run: pre-commit run --all-files
