name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja

jobs:
  cl:
    name: CL
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: choco install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan profile detect -f

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake config
        run: >
          cmake
          -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake

      - name: CMake build
        run: cmake --build build --config Release
