name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja

jobs:
  cl:
    name: CL
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: choco install ninja

      - name: Install conan
        run: |
          pip3 install "conan==1.61.0"
          conan config init
          conan config set general.revisions_enabled=1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake config
        run: cmake -S. -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: CMake build
        run: cmake --build build --config Release
