name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja

jobs:
  msvc:
    name: MSVC
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ninja
        run: choco install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan profile detect -f

      - name: Install clang
        uses: egor-tensin/setup-clang@v1

      - name: CMake config
        run: >
          cmake
          -S .
          -B build
          -G Ninja
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake

      - name: CMake build
        run: cmake --build build
